# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-04 23:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gantt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_dev_trf',
            fields=[
                ('dev_trf_id', models.AutoField(primary_key=True, serialize=False)),
                ('fk_dev_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gantt.tb_desenvolvedor')),
                ('fk_trf_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gantt.tb_tarefa')),
            ],
        ),
    ]
