# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-04 23:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gantt', '0002_tb_dev_trf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tb_dev_trf',
            name='fk_dev_id',
        ),
        migrations.RemoveField(
            model_name='tb_dev_trf',
            name='fk_trf_id',
        ),
        migrations.DeleteModel(
            name='tb_dev_trf',
        ),
    ]
