# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-04 23:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gantt', '0008_auto_20200304_2053'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tb_dev_trf',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='tb_dev_trf',
            name='fk_dev_id',
        ),
        migrations.RemoveField(
            model_name='tb_dev_trf',
            name='fk_trf_id',
        ),
        migrations.RemoveField(
            model_name='tb_tarefa',
            name='fk_prj_id',
        ),
        migrations.DeleteModel(
            name='tb_desenvolvedor',
        ),
        migrations.DeleteModel(
            name='tb_Dev_Trf',
        ),
        migrations.DeleteModel(
            name='tb_projeto',
        ),
        migrations.DeleteModel(
            name='tb_tarefa',
        ),
    ]
