# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-03-04 23:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gantt', '0009_auto_20200304_2054'),
    ]

    operations = [
        migrations.CreateModel(
            name='tb_Desenvolvedor',
            fields=[
                ('dev_id', models.AutoField(primary_key=True, serialize=False)),
                ('dev_nome', models.CharField(max_length=90)),
                ('dev_contato', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='tb_Dev_Trf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_dev_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gantt.tb_Desenvolvedor')),
            ],
        ),
        migrations.CreateModel(
            name='tb_Projeto',
            fields=[
                ('prj_id', models.AutoField(primary_key=True, serialize=False)),
                ('prj_nome', models.CharField(max_length=60)),
                ('prj_escopo', models.CharField(max_length=119)),
                ('prj_datainicio', models.DateField()),
                ('prj_prazoentrega', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='tb_Tarefa',
            fields=[
                ('trf_id', models.AutoField(primary_key=True, serialize=False)),
                ('trf_datainicial', models.DateField()),
                ('trf_datafinal', models.DateField(null=True)),
                ('trf_prazo', models.DateField()),
                ('trf_interdependencia', models.IntegerField(null=True)),
                ('trf_entregavel', models.BooleanField(default=False)),
                ('fk_prj_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gantt.tb_Projeto')),
            ],
        ),
        migrations.AddField(
            model_name='tb_dev_trf',
            name='fk_trf_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gantt.tb_Tarefa'),
        ),
        migrations.AlterUniqueTogether(
            name='tb_dev_trf',
            unique_together=set([('fk_dev_id', 'fk_trf_id')]),
        ),
    ]
