# Generated by Django 3.0.6 on 2020-05-07 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gantt', '0010_auto_20200304_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tb_desenvolvedor',
            name='dev_contato',
            field=models.BigIntegerField(verbose_name='Contato'),
        ),
        migrations.AlterField(
            model_name='tb_desenvolvedor',
            name='dev_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='tb_desenvolvedor',
            name='dev_nome',
            field=models.CharField(max_length=90, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='tb_projeto',
            name='prj_datainicio',
            field=models.DateField(verbose_name='Data Inicio'),
        ),
        migrations.AlterField(
            model_name='tb_projeto',
            name='prj_escopo',
            field=models.CharField(max_length=119, verbose_name='Escopo'),
        ),
        migrations.AlterField(
            model_name='tb_projeto',
            name='prj_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='tb_projeto',
            name='prj_nome',
            field=models.CharField(max_length=60, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='tb_projeto',
            name='prj_prazoentrega',
            field=models.DateField(verbose_name='Prazo de Entrega'),
        ),
        migrations.AlterField(
            model_name='tb_tarefa',
            name='trf_datafinal',
            field=models.DateField(null=True, verbose_name='Data Final'),
        ),
        migrations.AlterField(
            model_name='tb_tarefa',
            name='trf_datainicial',
            field=models.DateField(verbose_name='Data Inicial'),
        ),
        migrations.AlterField(
            model_name='tb_tarefa',
            name='trf_entregavel',
            field=models.BooleanField(default=False, verbose_name='Entregavel'),
        ),
        migrations.AlterField(
            model_name='tb_tarefa',
            name='trf_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterField(
            model_name='tb_tarefa',
            name='trf_interdependencia',
            field=models.IntegerField(null=True, verbose_name='Interdenpencia'),
        ),
        migrations.AlterField(
            model_name='tb_tarefa',
            name='trf_prazo',
            field=models.DateField(verbose_name='Prazo'),
        ),
    ]
