# Generated by Django 3.0.6 on 2020-05-07 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gantt', '0011_auto_20200507_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_tarefa',
            name='trf_name',
            field=models.CharField(default='', max_length=120, verbose_name='nome'),
        ),
    ]
