# Generated by Django 3.0.6 on 2020-05-24 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gantt', '0012_tb_tarefa_trf_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tb_projeto',
            name='prj_color',
            field=models.CharField(default='', max_length=60, verbose_name='Cor'),
        ),
    ]
